### PR TITLE
Us189412

### PR DESCRIPTION
**Pull request by shalabgoel**
PredixUIKit:  Create chart matching MOS line graph

### CODE REVIEW

**Comment by andyjohns** [comment]
Can one of the admins verify this patch?

**Comment by jeremyosterhoudt** [comment]
ok to test

**Comment by andyjohns** [comment]
retest this please

**Comment by andyjohns** [comment]
retest this please

**Comment by andyjohns** [comment]
retest this please

**Comment by andyjohns** [comment]
retest this please

**Comment by andyjohns** [comment]
retest this please

**Comment by jeremyosterhoudt** [comment]
retest this please

**Pull request closed without merging**
